/*

 SPRITE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char sprite[] =
{
  0x7E,0x7E,0x99,0x99,0x81,0x81,0xA5,0xA5,
  0x81,0x81,0xDB,0xDB,0xC3,0xC3,0x3C,0x3C
};

/* End of SPRITE.C */
