/*

 UFO.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char ufo[] =
{
  0x5A,0x3C,0xE3,0x42,0x7C,0x99,0xEB,0xA5,
  0xFB,0xA5,0x66,0x99,0xE7,0x42,0x5A,0x3C
};

/* End of UFO.C */
