/*

 WINDOW.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 4
   Tile set      : P:\Homebrew\GB\gbdk_playground\window\border.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 152
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define windowWidth 20
#define windowHeight 4
#define windowBank 0

extern unsigned char window[];

/* End of WINDOW.H */
