/*

 BG_TILE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const unsigned char BGTile[] =
{
  0xFF,0xFF,0xFB,0xFB,0xFF,0xFF,0xFF,0xFF,
  0xFF,0xFF,0x7F,0x7F,0xF7,0xF7,0xFF,0xFF
};

/* End of BG_TILE.C */
